apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-basic-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
      env: dev
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: xaprun/nginx-html:v1.0
          ports:
            - containerPort: 80
