apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-service
  namespace: default
spec:
  selector:
    app: aspnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort
