apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvLXNlcnZpY2U6MjcwMTcvbXlkYj9hdXRoU291cmNlPWFkbWluLG1vbmdvZGI6Ly9yb290OmV4YW1wbGVAcm9vdEBtb25nby0xLm1vbmdvLXNlcnZpY2U6MjcwMTcvbXlkYj9hdXRoU291cmNlPWFkbWlu
