apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-basic-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-basic
  template:
    metadata:
      labels:
        app: nginx-basic
        env: stag
    spec:
      containers:
        - name: example-container
          image: xaprun/nginx-html:v1.0
          ports:
            - containerPort: 80
