apiVersion: v1
kind: Service
metadata:
  name: nginx-basic-service
  namespace: default
spec:
  selector:
    app: nginx-basic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP